version: '3.9'
services:
  audio_classifier:
    container_name: audio_classifier
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./src/audio_classifier:/src/audio_classifier
      - $HOME/.config/pulse:/home/.config/pulse
    stdin_open: true
    # TODO: get microphone mounted
    environment:
      - PULSE_SERVER=host.docker.internal
    entrypoint: ["tail", "-f", "/dev/null"]
    

volumes:
  audio_classifier:
